services:
  postgres:
    image: postgres:17-alpine
    container_name: vkbot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vkbot_network
    restart: always

  vkbot:
    build:
      context: ./VKBot
      dockerfile: Dockerfile
    container_name: vkbot
    environment:
      ConnectionStrings__PostgreSQL: "${POSTGRES_CONNECTION}"

      VK__AccessToken: "${VK_ACCESS_TOKEN}"
      VK__GroupId: "${VK_GROUP_ID}"
    #depends_on:
      # - postgres
    networks:
      - vkbot_network
    restart: always

volumes:
  postgres_data:

networks:
  vkbot_network:
    driver: bridge