// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VKBot.Features.Core.Data;

#nullable disable

namespace VKBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909081758_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("GroupNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableReminder")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReminderSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserVkUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserVkUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.MessageDelivery", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DispatchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isRead")
                        .HasColumnType("boolean");

                    b.HasKey("MessageId", "RecipientId");

                    b.HasIndex("RecipientId");

                    b.ToTable("MessageDeliveries");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.User", b =>
                {
                    b.Property<long>("VkUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VkUserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VkUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            VkUserId = 651565729L,
                            FullName = "Admin 1",
                            IsBlocked = false,
                            IsConfirmed = true,
                            IsDeleted = false,
                            Role = "Admin"
                        },
                        new
                        {
                            VkUserId = 562436407L,
                            FullName = "Admin 2",
                            IsBlocked = false,
                            IsConfirmed = true,
                            IsDeleted = false,
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.Message", b =>
                {
                    b.HasOne("VKBot.Features.Core.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VKBot.Features.Core.Domain.Entities.User", null)
                        .WithMany("RereceivedMessages")
                        .HasForeignKey("UserVkUserId");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.MessageDelivery", b =>
                {
                    b.HasOne("VKBot.Features.Core.Domain.Entities.Message", "Message")
                        .WithMany("MessageDeliveries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VKBot.Features.Core.Domain.Entities.User", "Recipient")
                        .WithMany("MessageDeliveries")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("VKBot.Features.Core.Domain.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.Message", b =>
                {
                    b.Navigation("MessageDeliveries");
                });

            modelBuilder.Entity("VKBot.Features.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("MessageDeliveries");

                    b.Navigation("RereceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
